trigger:
- main

pool:
  name: vmss-agent

jobs:
  - job: job1
    steps:
    - script: |
        echo Hello 1, $(HOSTNAME)
  - job: job2
    steps:
    - script: |
        echo Hello 2, $(HOSTNAME)

